
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/onoe

    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

  h2:
    console:
      enabled: true
  jpa:
    # ?? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

    # ??? ?? ?? data.sql ??
    defer-datasource-initialization: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot